EVT_RECV_ARM_MSG = 1

SKY_SERVER_CMD_CONN_BUILD = 0
SKY_SERVER_CMD_SET = 2
SKY_SERVER_CMD_START_SHUFFLE = 13
SKY_SERVER_CMD_SET_SHUFFLER = 14
SKY_SERVER_CMD_DEAL_CARD = 21
SKY_SERVER_CMD_RESET_CARD_COUNT = 27
SKY_SERVER_CMD_SHUFFLE_DEAL = 42
SKY_SERVER_CMD_PUSH_SHUFFLE_PUSH = 44



SKY_BALL5_CMD_RECV_CMD = 100
SKY_BALL5_CMD_CONN_BUILD = 101
SKY_BALL5_CMD_OPEN_CARD = 111
SKY_BALL5_CMD_EXE = 134 #arm has executed the command

SKY_SHUFFER_0 = 0
SKY_SHUFFER_1 = 1

SKY_BRANDBOOT_1 = 1
SKY_BRANDBOOT_2 = 2

